export const COMMANDS = [
  "/ask",
  "/plan",
  "/reflect",
  "/progress",
  "/profile",
  "/goals",
  "/goals voice",
  "/goals reset",
  "/connect",
  "/trading",
  "/alpaca",
  "/portfolio",
  "/emails",
  "/calendar",
  "/linkedin",
  "/linkedin data",
  "/oura",
  "/models",
  "/mcp-tools",
  "/health",
  "/project",
  "/projects",
  "/work",
  "/finances",
  "/family",
  "/growth",
  "/education",
  "/websites",
  "/sync",
  "/memory",
  "/github",
  "/wealth",
  "/tickers",
  "/data",
  "/insights",
  "/report",
  "/mentors",
  "/habits",
  "/notify",
  "/recs",
  "/review",
  "/dashboard",
  "/account",
  "/morning",
  "/focus",
  "/learn",
  "/reset",
  "/logout",
  "/clear",
  "/help"
];

export const COMMAND_DESCRIPTIONS = {
  "/ask": "Ask Claude anything about your life or goals",
  "/plan": "Create or review your daily/weekly plan",
  "/reflect": "Reflect on progress and get insights",
  "/progress": "View overall progress score and goal completion status",
  "/profile": "View profile: /profile general | work | startup | education | health | finance | skills | goals | social",
  "/goals": "Voice-guided goal setting (requires OpenAI) or /goals set <category> | /goals reset",
  "/connect": "Set up integrations (LinkedIn, Oura, Alpaca, etc.)",
  "/trading": "Enable/disable auto-trading and view status",
  "/alpaca": "Alpaca setup - /alpaca live|paper, swing|options, conservative|risky, keys, status",
  "/portfolio": "View portfolio summary",
  "/emails": "Email integration settings",
  "/calendar": "Calendar integration settings",
  "/linkedin": "Open browser, capture LinkedIn profile, save URL and data",
  "/linkedin data": "Show stored LinkedIn profile data from recent crawl",
  "/oura": "Oura Ring integration - health metrics",
  "/models": "AI models - Connect OpenAI, Anthropic, Google. Ctrl+T cycles tiers (low/medium/high/xhigh)",
  "/mcp-tools": "List available MCP servers and tools",
  "/health": "Health domain focus - Oura metrics",
  "/project": "Create/manage projects: /project new <name> | /project action <project> <action> | /project list",
  "/projects": "Alias: list projects",
  "/work": "Work domain focus",
  "/finances": "Personal Capital integration - /finances connect, /finances status, /finances 2fa <code>",
  "/family": "Family domain focus",
  "/growth": "Growth domain focus",
  "/education": "Education domain - grad school, college detection",
  "/websites": "Website projects focus",
  "/sync": "Cloud sync status for mobile access",
  "/memory": "View or manage memory files",
  "/github": "GitHub integration for private repo backup",
  "/wealth": "Wealth management - Plaid, Robinhood, Personal Capital",
  "/tickers": "View top scoring tickers from Yahoo Finance",
  "/data": "Data scheduler - /data status, /data refresh, /data actions",
  "/insights": "Get AI-powered insights about your life trajectory",
  "/report": "Generate progress report - /report daily, /report weekly",
  "/mentors": "Learn from successful people - /mentors <category>",
  "/habits": "Track daily habits - /habits, /habits add <name>, /habits complete <#>",
  "/notify": "Send notifications - /notify daily, /notify weekly, /notify status",
  "/recs": "AI recommendations - /recs, /recs refresh, /recs done <#>, /recs dismiss <#>",
  "/review": "Weekly review - /review, /review start, /review history, /review stats",
  "/dashboard": "Life dashboard - comprehensive overview of all life metrics",
  "/account": "Accountability - /account, /account checkin, /account commit <text>, /account done <#>",
  "/morning": "Morning briefing - get your daily briefing with priorities",
  "/focus": "Focus timer - /focus start [task], /focus deep, /focus end, /focus pause/resume",
  "/learn": "Learning tracker - /learn, /learn add <title>, /learn progress <#> <percent>, /learn done",
  "/reset": "Reset all data - requires two confirmations to delete",
  "/logout": "Log out and return to onboarding",
  "/clear": "Clear conversation history",
  "/help": "Show available commands"
};
