export const COMMANDS = [
  "/ask",
  "/plan",
  "/reflect",
  "/progress",
  "/profile",
  "/talk",
  "/thesis",
  "/thesis beliefs",
  "/thesis projects",
  "/thesis trigger",
  "/thesis add-belief",
  "/knowledge",
  "/backlog",
  "/backlog add",
  "/backlog boost",
  "/backlog dismiss",
  "/idle",
  "/idle on",
  "/idle off",
  "/idle work",
  "/goals",
  "/goals reset",
  "/connect",
  "/connect email",
  "/connect phone",
  "/trading",
  "/alpaca",
  "/portfolio",
  "/emails",
  "/calendar",
  "/linkedin",
  "/linkedin data",
  "/linkedin refresh",
  "/linkedin update",
  "/oura",
  "/models",
  "/mcp-tools",
  "/health",
  "/project",
  "/projects",
  "/work",
  "/finances",
  "/family",
  "/growth",
  "/education",
  "/websites",
  "/sync",
  "/memory",
  "/github",
  "/wealth",
  "/top stocks",
  "/top stocks detail",
  "/run stock sweep",
  "/run stock refresh",
  "/update stock tickers",
  "/data",
  "/insights",
  "/report",
  "/mentors",
  "/role model",
  "/role model refresh",
  "/role model history",
  "/role model why",
  "/cron",
  "/disaster",
  "/disaster categories",
  "/disaster assess",
  "/linkedin history",
  "/linkedin agent",
  "/linkedin agent status",
  "/habits",
  "/notify",
  "/recs",
  "/review",
  "/dashboard",
  "/account",
  "/morning",
  "/focus",
  "/learn",
  "/skill",
  "/skill create",
  "/skill list",
  "/skill edit",
  "/skill delete",
  "/skill show",
  "/skill learn",
  "/skill pull",
  "/skill gaps",
  "/skill repos",
  "/excel",
  "/excel list",
  "/excel read",
  "/excel create",
  "/backup",
  "/backup now",
  "/backup status",
  "/backup restore",
  "/sync firebase",
  "/call",
  "/call status",
  "/call end",
  "/update",
  "/update check",
  "/reset",
  "/profiles",
  "/logout",
  "/clear",
  "/help"
];

export const COMMAND_DESCRIPTIONS = {
  "/ask": "Ask Claude anything about your life or goals",
  "/plan": "Create or review your daily/weekly plan",
  "/reflect": "Reflect on progress and get insights",
  "/progress": "View overall progress score and goal completion status",
  "/profile": "View profile: /profile general | work | startup | education | health | finance | skills | goals | social",
  "/talk": "Start a voice conversation",
  "/thesis": "View current thesis and focus - /thesis beliefs | /thesis projects | /thesis trigger | /thesis add-belief",
  "/knowledge": "AI knowledge depth breakdown — see how much the AI knows across all domains",
  "/backlog": "View backlog of ideas - /backlog add <title> | /backlog boost <id> <score> | /backlog dismiss <id>",
  "/idle": "Idle processor status - /idle on | /idle off | /idle work (force work now)",
  "/goals": "Goal setting - /goals set <category> | /goals reset",
  "/connect": "Set up integrations — /connect phone (install PWA for notifications), /connect email",
  "/connect email": "Connect Google Gmail & Calendar via OAuth",
  "/trading": "Enable/disable auto-trading and view status",
  "/alpaca": "Alpaca setup - /alpaca live|paper, swing|options, conservative|risky, keys, status",
  "/portfolio": "View portfolio summary",
  "/emails": "Email integration settings",
  "/calendar": "Calendar integration settings",
  "/linkedin": "Open browser, capture LinkedIn profile, save URL and data",
  "/linkedin data": "Show stored LinkedIn profile data from recent crawl",
  "/linkedin refresh": "Force a fresh LinkedIn scrape with full-page scroll",
  "/linkedin update": "Full LinkedIn update via browser agent + screenshot extraction",
  "/linkedin history": "View LinkedIn profile snapshot timeline — track changes over time, posts history",
  "/oura": "Oura Ring integration - health metrics",
  "/models": "AI models - Connect OpenAI, Anthropic, Google. Ctrl+T cycles tiers (low/medium/high/xhigh)",
  "/mcp-tools": "List available MCP servers and tools",
  "/health": "Health domain focus - Oura metrics",
  "/project": "Create/manage projects: /project new <name> | /project action <project> <action> | /project list",
  "/projects": "Alias: list projects",
  "/work": "Work domain focus",
  "/finances": "Personal Capital integration - /finances connect, /finances status, /finances 2fa <code>",
  "/family": "Family domain focus",
  "/growth": "Growth domain focus",
  "/education": "Education domain - grad school, college detection",
  "/websites": "Website projects focus",
  "/sync": "Cloud sync - /sync firebase (push tickers/profile to Firestore)",
  "/memory": "View or manage memory files",
  "/github": "GitHub integration for private repo backup",
  "/wealth": "Wealth management - Plaid, Robinhood, Personal Capital",
  "/top stocks": "Refresh and show top 10 stocks by score with signal, price, and change%",
  "/top stocks detail": "Top 5 with full breakdown: MACD, Volume σ, Psych, RSI, and score components",
  "/run stock sweep": "Full 800+ ticker sweep with scoring",
  "/run stock refresh": "Refresh core ticker prices",
  "/update stock tickers": "View top scored tickers",
  "/data": "Data scheduler - /data status, /data refresh, /data actions",
  "/insights": "Get AI-powered insights about your life trajectory",
  "/report": "Generate progress report - /report daily, /report weekly",
  "/mentors": "Learn from successful people - /mentors <category>",
  "/role model": "Top 5 role models - /role model, /role model refresh, /role model <name>, /role model history, /role model why",
  "/cron": "View scheduled cron jobs — daily, weekly, monthly job schedule with run counts",
  "/disaster": "Disaster & crisis tracker — 15 threat domains: markets, credit, bonds, housing, geopolitical, jobs, food, energy, climate, natural disasters, biological, space, AI/tech, societal, devastation",
  "/disaster categories": "View all disaster categories and what we track for you (overlay view)",
  "/disaster assess": "Run a full threat assessment with web research across all 15 domains",
  "/habits": "Track daily habits - /habits, /habits add <name>, /habits complete <#>",
  "/notify": "Send notifications - /notify daily, /notify weekly, /notify status",
  "/recs": "AI recommendations - /recs, /recs refresh, /recs done <#>, /recs dismiss <#>",
  "/review": "Weekly review - /review, /review start, /review history, /review stats",
  "/dashboard": "Life dashboard - comprehensive overview of all life metrics",
  "/account": "Accountability - /account, /account checkin, /account commit <text>, /account done <#>",
  "/morning": "Morning briefing - get your daily briefing with priorities",
  "/focus": "Focus timer - /focus start [task], /focus deep, /focus end, /focus pause/resume",
  "/learn": "Learning tracker - /learn, /learn add <title>, /learn progress <#> <percent>, /learn done",
  "/skill": "Custom skills - /skill list, /skill create <name>, /skill show <name>, /skill edit <name>, /skill delete <name>, /skill learn, /skill pull <query>, /skill gaps, /skill repos",
  "/excel": "Excel spreadsheets - /excel list, /excel read <name>, /excel create <name>",
  "/backup": "Firebase backup - /backup now, /backup status, /backup restore",
  "/call": "Call your phone via Vapi AI voice — /call status, /call end",
  "/update": "Check for and apply updates — /update check (check only, no install)",
  "/reset": "Reset all data - requires two confirmations to delete",
  "/profiles": "List archived user profiles",
  "/logout": "Log out and return to onboarding",
  "/clear": "Clear conversation history",
  "/help": "Show available commands"
};
